### PR TITLE
USB CDC UART Bridge

### PR DESCRIPTION
**Pull request by davidthings**
This set of changes adds this capability to pico-dirtyJtag.

There are a few changes:
- there is now a new file dirtyJtagConfig.h which holds crucial definitions like the pin on which the JTAG interface is exposed and whether the USB CDC - UART bridge is enabled
- a BOARD_TYPE variable determines what the target board is
- there is a simple LED abstraction that allows some visual feedback when data is being exchanged.

### CODE REVIEW

**Comment by phdussud** [comment]
The code looks good. I think it would be good to update the readme to describe the new feature briefly.

**Comment by davidthings** [comment]
Will do.

**Comment by davidthings** [comment]
Might have gone a little overboard there.  I won't be offended if you edit / refactor.  Code or doc!

**Comment by phdussud** [comment]
All done! David, thank you so much for this contribution.

**Pull request merged**
